import { ArrowRight, CalendarDays, Check, Clock3, CircleDollarSign, Download, FileText, MapPin, MoreHorizontal, Ship, Users } from "lucide-react";
import Link from "next/link";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeader, SectionTitle, Stat, StatusBadge } from "@/components/HrisUI";
import { Button } from "@/components/ui/button";
import { approvals } from "@/lib/hris-data";

const chart = [{d:"Sen",h:147,t:4},{d:"Sel",h:151,t:6},{d:"Rab",h:149,t:3},{d:"Kam",h:154,t:5},{d:"Jum",h:152,t:7},{d:"Sab",h:83,t:2},{d:"Min",h:79,t:1}];
export function DashboardPage() {
 return <div className="space-y-7"><PageHeader eyebrow="Rabu, 15 Juli 2026" title="Selamat siang, Nico" description="Berikut kondisi tenaga kerja PT MMS hari ini." actions={<><Button variant="outline"><Download className="size-4"/> Unduh laporan</Button><Button asChild><Link href="/attendance"><Clock3 className="size-4"/> Catat kehadiran</Link></Button></>}/>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Karyawan aktif" value="184" note="+6 bulan ini" icon={Users} tone="good"/><Stat label="Hadir hari ini" value="152" note="92,1% tingkat hadir" icon={Check} tone="good"/><Stat label="Menunggu approval" value="12" note="4 membutuhkan Anda" icon={Clock3} tone="warn"/><Stat label="Payroll Juli" value="Review" note="Rp 1,24 M · 184 karyawan" icon={CircleDollarSign}/></div>
 <div className="grid gap-5 xl:grid-cols-[1.45fr_.8fr]"><section className="rounded-lg border bg-card p-5"><SectionTitle title="Kehadiran minggu ini" subtitle="Data terpadu GPS, fingerprint, dan sign on/off" action={<Button variant="ghost" size="sm" asChild><Link href="/attendance">Lihat detail <ArrowRight/></Link></Button>}/><div className="h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{left:-22,right:8,top:12}}><defs><linearGradient id="mono" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="currentColor" stopOpacity=".16"/><stop offset="1" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><CartesianGrid strokeDasharray="2 4" vertical={false}/><XAxis dataKey="d" axisLine={false} tickLine={false} fontSize={11}/><YAxis axisLine={false} tickLine={false} fontSize={11}/><Tooltip contentStyle={{borderRadius:6,fontSize:12}}/><Area type="monotone" dataKey="h" name="Hadir" stroke="currentColor" strokeWidth={2} fill="url(#mono)"/></AreaChart></ResponsiveContainer></div><div className="mt-2 flex gap-5 border-t pt-4 text-xs text-muted-foreground"><span><b className="text-foreground">+2,4%</b> vs minggu lalu</span><span><b className="text-foreground">28</b> personel on-board</span><span><b className="text-foreground">7</b> terlambat</span></div></section>
 <section className="rounded-lg border bg-foreground p-5 text-background"><div className="flex items-start justify-between"><div><p className="text-xs text-background/60">Absensi mobile</p><h2 className="mt-1 text-xl font-semibold">Siap check in?</h2></div><MapPin className="size-5 text-background/60"/></div><div className="my-6 rounded-md border border-background/15 bg-background/5 p-4"><div className="flex items-center gap-3"><span className="size-2 rounded-full bg-emerald-400"/><div><p className="text-sm font-medium">Jakarta Head Office</p><p className="text-xs text-background/55">Dalam radius · akurasi 8 m</p></div></div></div><p className="text-4xl font-semibold tabular-nums tracking-[-.04em]">13:07</p><p className="mt-1 text-xs text-background/55">Shift kantor · 08:00–17:00 WIB</p><Button className="mt-6 w-full bg-background text-foreground hover:bg-background/90"><Clock3/> Check in dengan GPS</Button></section></div>
 <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="rounded-lg border bg-card p-5"><SectionTitle title="Menunggu tindakan Anda" subtitle="Approval lintas modul" action={<StatusBadge tone="warn">4 pending</StatusBadge>}/><div className="divide-y">{approvals.map((a,i)=><div key={a.id} className="flex items-center gap-3 py-3"><div className="grid size-9 shrink-0 place-items-center rounded-md bg-muted">{i===0?<CalendarDays className="size-4"/>:i===1?<Clock3 className="size-4"/>:i===2?<FileText className="size-4"/>:<Ship className="size-4"/>}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{a.person} · {a.type}</p><p className="truncate text-xs text-muted-foreground">{a.detail} · {a.time}</p></div><Button size="sm" variant="outline" asChild><Link href="/approvals">Review</Link></Button></div>)}</div></section>
 <section className="rounded-lg border bg-card p-5"><SectionTitle title="Agenda terdekat" subtitle="Cuti, kontrak, dan agenda perusahaan"/><div className="space-y-4">{[["16","JUL","Lina Amelia · Izin","1 hari"],["18","JUL","Fajar Setiawan · Cuti","3 hari"],["21","JUL","Kontrak Budi Pratama","Berakhir 30 hari lagi"],["25","JUL","Finalisasi payroll","Deadline Finance"]].map(e=><div key={e[0]+e[2]} className="flex gap-3"><div className="w-11 rounded-md border py-1 text-center"><b className="block text-sm">{e[0]}</b><span className="text-[9px] text-muted-foreground">{e[1]}</span></div><div><p className="text-sm font-medium">{e[2]}</p><p className="text-xs text-muted-foreground">{e[3]}</p></div><MoreHorizontal className="ml-auto size-4 text-muted-foreground"/></div>)}</div></section></div></div>;
}
