"use client";
import { Activity, Anchor, BarChart3, Bell, CalendarClock, CalendarDays, CheckCheck, ChevronRight, CircleDollarSign, Clock3, FileText, History, LayoutDashboard, LogOut, Network, ReceiptText, Settings, ShieldCheck, Target, Users, WalletCards } from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { logout } from "@/lib/session";
import { Avatar, AvatarFallback } from "./ui/avatar";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "./ui/dropdown-menu";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarMenu, SidebarMenuButton, SidebarMenuItem, useSidebar } from "./ui/sidebar";
const groups=[{label:"Command center",items:[{href:"/dashboard",label:"Executive overview",icon:LayoutDashboard},{href:"/analytics",label:"People analytics",icon:BarChart3},{href:"/approvals",label:"Approval inbox",icon:CheckCheck,badge:"4"},{href:"/notifications",label:"Notifications",icon:Bell,badge:"3"}]},{label:"Workforce",items:[{href:"/employees",label:"People directory",icon:Users},{href:"/organization",label:"Organization",icon:Network},{href:"/attendance",label:"Time & attendance",icon:Clock3},{href:"/scheduling",label:"Shift & roster",icon:CalendarClock},{href:"/leave",label:"Leave & absence",icon:CalendarDays}]},{label:"Maritime operations",items:[{href:"/fleet",label:"Fleet & crewing",icon:Anchor},{href:"/compliance",label:"Compliance",icon:ShieldCheck,badge:"17"}]},{label:"Pay & talent",items:[{href:"/payroll",label:"Payroll runs",icon:CircleDollarSign},{href:"/compensation",label:"Compensation",icon:WalletCards},{href:"/claims",label:"Claims & benefits",icon:ReceiptText},{href:"/performance",label:"Performance",icon:Target}]},{label:"Governance",items:[{href:"/letters",label:"Letters & documents",icon:FileText},{href:"/audit",label:"Audit trail",icon:History},{href:"/settings",label:"System settings",icon:Settings}]}];
function Nav(){const path=usePathname();const{setOpenMobile}=useSidebar();return <SidebarContent className="px-2 py-3">{groups.map(g=><SidebarGroup key={g.label} className="shrink-0 p-0 pb-4"><SidebarGroupLabel className="px-2 text-[9px] font-semibold uppercase tracking-[.16em]">{g.label}</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{g.items.map(i=><SidebarMenuItem key={i.href}><SidebarMenuButton asChild isActive={path===i.href} className="h-8"><Link href={i.href} onClick={()=>setOpenMobile(false)}><i.icon/><span>{i.label}</span>{i.badge&&<span className="ml-auto rounded-full border px-1.5 text-[9px]">{i.badge}</span>}</Link></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup>)}</SidebarContent>}
function User(){const router=useRouter();return <SidebarFooter className="border-t p-2"><div className="mb-1 flex items-center gap-2 rounded-md bg-emerald-50 px-2 py-1.5 text-[10px] text-emerald-800"><Activity className="size-3"/> All systems operational</div><SidebarMenu><SidebarMenuItem><DropdownMenu><DropdownMenuTrigger asChild><SidebarMenuButton size="lg"><Avatar className="size-8"><AvatarFallback className="bg-foreground text-background text-xs">NA</AvatarFallback></Avatar><div className="min-w-0 flex-1 text-left"><p className="truncate text-sm font-medium">Nico Admin</p><p className="truncate text-[10px] text-muted-foreground">Super Admin · Jakarta HQ</p></div><ChevronRight className="size-3"/></SidebarMenuButton></DropdownMenuTrigger><DropdownMenuContent side="top" align="start" className="w-60"><DropdownMenuItem asChild><Link href="/settings"><Settings/>System settings</Link></DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem onClick={()=>{logout();router.push("/")}} className="text-destructive"><LogOut/>Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></SidebarMenuItem></SidebarMenu></SidebarFooter>}
export function AppSidebar(){return <Sidebar collapsible="icon"><SidebarHeader className="h-16 justify-center border-b px-3"><Link href="/dashboard" className="flex items-center gap-2.5 overflow-hidden"><span className="grid size-8 shrink-0 place-items-center rounded-md bg-foreground text-background"><Anchor className="size-5"/></span><span><b className="block text-sm">MMS People</b><span className="block text-[9px] uppercase tracking-wider text-muted-foreground">Enterprise HR Cloud</span></span></Link></SidebarHeader><Nav/><User/></Sidebar>}
