"use client";
import { useState } from "react";
import { Anchor, ArrowRight, CheckCircle2, Eye, EyeOff, LockKeyhole, ShieldCheck, UserRound } from "lucide-react";
import { login } from "@/lib/session";

export function LoginScreen({onSuccess}:{onSuccess:()=>void}){
 const [username,setUsername]=useState(""); const [password,setPassword]=useState(""); const [show,setShow]=useState(false); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
 function submit(e:React.FormEvent){e.preventDefault();setError("");setLoading(true);setTimeout(()=>{if(login(username,password))onSuccess();else{setError("Username atau password tidak sesuai.");setLoading(false)}},420)}
 return <main className="min-h-screen bg-[#f3f4f1] p-3 text-slate-950 sm:p-5"><div className="mx-auto grid min-h-[calc(100vh-1.5rem)] max-w-[1500px] overflow-hidden rounded-[28px] border border-black/10 bg-white shadow-[0_25px_80px_rgba(15,23,42,.12)] sm:min-h-[calc(100vh-2.5rem)] lg:grid-cols-[1.08fr_.92fr]">
  <section className="relative hidden overflow-hidden bg-[#081713] p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(255,255,255,.06)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.06)_1px,transparent_1px)] [background-size:44px_44px]"/><div className="absolute -right-28 top-28 size-[460px] rounded-full border border-emerald-300/15"/><div className="absolute -right-6 top-50 size-[290px] rounded-full border border-emerald-300/25"/>
   <div className="relative flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl border border-white/15 bg-white/10"><Anchor className="size-5"/></span><div><b className="block tracking-tight">MMS People</b><span className="text-[10px] uppercase tracking-[.24em] text-emerald-100/60">Enterprise HR Cloud</span></div></div>
   <div className="relative max-w-xl"><span className="mb-6 inline-flex items-center gap-2 rounded-full border border-emerald-200/20 bg-emerald-300/10 px-3 py-1.5 text-[11px] font-medium text-emerald-100"><span className="size-1.5 rounded-full bg-emerald-300"/> Maritime workforce, synchronized.</span><h1 className="text-5xl font-semibold leading-[1.04] tracking-[-.045em]">People operations built for life at sea.</h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-300">Kelola kru, armada, payroll, compliance, dan performa dalam satu command center untuk PT Multi Maritim Shipping.</p></div>
   <div className="relative grid grid-cols-3 gap-3">{[["192","People"],["12","Vessels"],["96.2%","Ready"]].map(([n,l])=><div key={l} className="border-t border-white/15 pt-4"><b className="block text-2xl">{n}</b><span className="text-xs text-slate-400">{l}</span></div>)}</div>
  </section>
  <section className="flex items-center justify-center px-6 py-10 sm:px-12 lg:px-20"><div className="w-full max-w-md"><div className="mb-10 flex items-center gap-3 lg:hidden"><span className="grid size-10 place-items-center rounded-xl bg-[#081713] text-white"><Anchor className="size-5"/></span><b>MMS People</b></div><div className="mb-8"><p className="mb-3 text-[11px] font-semibold uppercase tracking-[.2em] text-emerald-700">Secure workspace</p><h2 className="text-4xl font-semibold tracking-[-.04em]">Selamat datang kembali</h2><p className="mt-3 text-sm leading-6 text-slate-500">Masuk ke command center MMS People untuk melanjutkan operasional.</p></div>
   <form onSubmit={submit} className="space-y-5"><label className="block"><span className="mb-2 block text-xs font-semibold">Username</span><div className="relative"><UserRound className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input autoFocus value={username} onChange={e=>setUsername(e.target.value)} placeholder="Masukkan username" className="h-13 w-full rounded-xl border border-slate-200 bg-slate-50 pl-11 pr-4 text-sm outline-none transition focus:border-emerald-700 focus:bg-white focus:ring-4 focus:ring-emerald-700/10"/></div></label><label className="block"><span className="mb-2 block text-xs font-semibold">Password</span><div className="relative"><LockKeyhole className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Masukkan password" className="h-13 w-full rounded-xl border border-slate-200 bg-slate-50 pl-11 pr-12 text-sm outline-none transition focus:border-emerald-700 focus:bg-white focus:ring-4 focus:ring-emerald-700/10"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400" aria-label="Tampilkan password">{show?<EyeOff className="size-4"/>:<Eye className="size-4"/>}</button></div></label>
   {error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs text-red-700">{error}</p>}<button disabled={loading} className="flex h-13 w-full items-center justify-center gap-2 rounded-xl bg-[#081713] text-sm font-semibold text-white transition hover:bg-emerald-950 disabled:opacity-70">{loading?"Memverifikasi...":"Masuk ke MMS People"}<ArrowRight className="size-4"/></button></form>
   <div className="mt-6 rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 size-4 text-emerald-700"/><div><p className="text-xs font-semibold">Akun demo</p><p className="mt-1 font-mono text-xs text-slate-500">admin / admin123</p></div></div></div><div className="mt-8 flex items-center justify-center gap-2 text-[11px] text-slate-400"><ShieldCheck className="size-3.5"/> Sesi lokal terenkripsi · Authorized personnel only</div>
  </div></section>
 </div></main>
}
